name: slog4s
baseurl: ''
description: Structured and contextual logging for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: example
markdown: kramdown
